[package]
name = "experimental"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
rand = "0.9.0"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
