[package]
name = "trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
pong = { path = "../game/pong" }
game-lib = { path = "../game/game-lib" }
core-crnn = { path = "../core-crnn" }
rand = "0.9.0"
rand_distr = "0.5.0"
ggez = "0.9.3"
rayon = "1.10.0"
serde = "1.0.217"
serde_json = "1.0.138"
